version: 2
general_options: &general_options
  docker:
    - image: circleci/node:12
  working_directory: ~/repo
jobs:
  checkout:
    <<: *general_options
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  dry-compile:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Try compiling code
          command: npm run check
  build:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run build -- --mode production
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy-production:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to production environment
          command: npx firebase-tools deploy --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN --only hosting
workflows:
  version: 2
  default:
    jobs:
      - checkout
      - dry-compile:
          requires:
            - checkout
      - build:
          requires:
            - dry-compile
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - build
